plugins:
  spoiler_ui_enabled:
    default: true
    client: true
  logs_ui_enabled:
    default: true
    client: true
  kbd_ui_enabled:
    default: true
    client: true
  strikethrough_ui_enabled:
    default: true
    client: true
  code_ui_enabled:
    default: true
    client: true
